---
title: "Assignment 2"
author: "Steve Hawley"
date: "November 18, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 0: Load the data and packages

```{r get_data, message=FALSE, results='markup'}
library(foreign) #for importing spss data
library(summarytools) #for descriptive and cross tables
library(dplyr) #for grouping and plotting
library(ggplot2) #for plotting
library(effsize) #for cohen's d
library(car) #for leven's test
library(sjstats) #for eta squared
library(tidyr) #for gather function

# import the spss file. Label the factors
data<-read.spss("Data+for+assignments.sav",to.data.frame = TRUE, add.undeclared.levels = "no")

#subset data for analysis
rma<-data %>% 
  select(code,age,gender,satcurwt,satwt18) %>% 
  filter(!is.na(satcurwt),!is.na(satwt18),!is.na(gender), age>18) %>% 
  mutate(ID = seq.int(n()))

# take a look at the data. See what the fields are
head(rma)

#inspect the data types
str(rma)


```

## Section 1: Pair-Samples t-test 



```{r paired_samples, results='asis'}

#subset the variables for paired samples t-test
pst<-rma %>% select(satcurwt,satwt18)

#get the descriptives
descr(pst, style = 'rmarkdown')

#run the t test
t.test(pst$satwt18, pst$satcurwt, paired = TRUE)

#effect size
cohen.d(pst$satwt18, pst$satcurwt, paired = TRUE)

```

## Section 2: Repeated-Measures ANOVA



```{r repmea_aov, results='asis'}

#Following the approach for repeated measures anova found here: http://www.cookbook-r.com/Statistical_analysis/ANOVA/#anovas-with-within-subjects-variables
#First I need to reshape the data from wide to long for this to work
longdata<-gather(rma,satis,value,satwt18:satcurwt)

#let's take a look
head(longdata)

#set up the data to plot. Order the factors
longdata$satis<-factor(longdata$satis, levels = c("satwt18","satcurwt"))

#group the data
p<-longdata %>% group_by(satis) %>% summarise(satscore=mean(value))

#line plot
p %>%
  ggplot(aes(x=satis, y=satscore, group=1)) +
  geom_line() +
  geom_point() +
  expand_limits(y=c(0,10))

#need to set the two timepoints (i.e., repeated IDs from the previously wide variables) as factors
longdata$ID<-factor(longdata$ID)

#Run the ANOVA
aov_long<-aov(value~satis + Error(ID/satis), data=longdata)
summary(aov_long)

eta_sq(aov_long)

```

## Section 3: Mixed ANOVA



```{r mixed_aov, results='asis'}

#For the mixed anova, I'll follow the approach from the same website as the previous section: http://www.cookbook-r.com/Statistical_analysis/ANOVA/#mixed-design-anova
aov.mix<-aov(value~satis*gender + Error(ID/(satis*gender)), data=longdata)
summary(aov.mix)

```
